local M = {}


local Highlight = require("gruber-darker.highlight")
local colors    = require("gruber-darker.colors")
local with      = require("gruber-darker.utils").with


M["GruberDarkerFg"]        = Highlight.new("GruberDarkerFg", { fg = colors["gruber-darker-fg"] })
M["GruberDarkerFgP1"]      = Highlight.new("GruberDarkerFgP1", { fg = colors["gruber-darker-fg+1"] })
M["GruberDarkerFgP2"]      = Highlight.new("GruberDarkerFgP2", { fg = colors["gruber-darker-fg+2"] })
M["GruberDarkerWhite"]     = Highlight.new("GruberDarkerWhite", { fg = colors["gruber-darker-white"] })
M["GruberDarkerBlack"]     = Highlight.new("GruberDarkerBlack", { fg = colors["gruber-darker-black"] })
M["GruberDarkerBgM1"]      = Highlight.new("GruberDarkerBgM1", { fg = colors["gruber-darker-bg-1"] })
M["GruberDarkerBg"]        = Highlight.new("GruberDarkerBg", { fg = colors["gruber-darker-bg"] })
M["GruberDarkerBgP1"]      = Highlight.new("GruberDarkerBgP1", { fg = colors["gruber-darker-bg+1"] })
M["GruberDarkerBgP2"]      = Highlight.new("GruberDarkerBgP2", { fg = colors["gruber-darker-bg+2"] })
M["GruberDarkerBgP3"]      = Highlight.new("GruberDarkerBgP3", { fg = colors["gruber-darker-bg+3"] })
M["GruberDarkerBgP4"]      = Highlight.new("GruberDarkerBgP4", { fg = colors["gruber-darker-bg+4"] })
M["GruberDarkerRedM1"]     = Highlight.new("GruberDarkerRedM1", { fg = colors["gruber-darker-red-1"] })
M["GruberDarkerRed"]       = Highlight.new("GruberDarkerRed", { fg = colors["gruber-darker-red"] })
M["GruberDarkerRedP1"]     = Highlight.new("GruberDarkerRedP1", { fg = colors["gruber-darker-red+1"] })
M["GruberDarkerGreen"]     = Highlight.new("GruberDarkerGreen", { fg = colors["gruber-darker-green"] })
M["GruberDarkerYellow"]    = Highlight.new("GruberDarkerYellow", { fg = colors["gruber-darker-yellow"] })
M["GruberDarkerBrown"]     = Highlight.new("GruberDarkerBrown", { fg = colors["gruber-darker-brown"] })
M["GruberDarkerQuartz"]    = Highlight.new("GruberDarkerQuartz", { fg = colors["gruber-darker-quartz"] })
M["GruberDarkerNiagaraM2"] = Highlight.new("GruberDarkerNiagaraM2", { fg = colors["gruber-darker-niagara-2"] })
M["GruberDarkerNiagaraM1"] = Highlight.new("GruberDarkerNiagaraM1", { fg = colors["gruber-darker-niagara-1"] })
M["GruberDarkerNiagara"]   = Highlight.new("GruberDarkerNiagara", { fg = colors["gruber-darker-niagara"] })
M["GruberDarkerWisteria"]  = Highlight.new("GruberDarkerWisteria", { fg = colors["gruber-darker-wisteria"] })


M["GruberDarkerFgBold"]        = Highlight.new("GruberDarkerFgBold", with(M["GruberDarkerFg"], { bold = true }))
M["GruberDarkerFgP1Bold"]      = Highlight.new("GruberDarkerFgP1Bold", with(M["GruberDarkerFgP1"], { bold = true }))
M["GruberDarkerFgP2Bold"]      = Highlight.new("GruberDarkerFgP2Bold", with(M["GruberDarkerFgP2"], { bold = true }))
M["GruberDarkerWhiteBold"]     = Highlight.new("GruberDarkerWhiteBold", with(M["GruberDarkerWhite"], { bold = true }))
M["GruberDarkerBlackBold"]     = Highlight.new("GruberDarkerBlackBold", with(M["GruberDarkerBlack"], { bold = true }))
M["GruberDarkerBgM1Bold"]      = Highlight.new("GruberDarkerBgM1Bold", with(M["GruberDarkerBgM1"], { bold = true }))
M["GruberDarkerBgBold"]        = Highlight.new("GruberDarkerBgBold", with(M["GruberDarkerBg"], { bold = true }))
M["GruberDarkerBgP1Bold"]      = Highlight.new("GruberDarkerBgP1Bold", with(M["GruberDarkerBgP1"], { bold = true }))
M["GruberDarkerBgP2Bold"]      = Highlight.new("GruberDarkerBgP2Bold", with(M["GruberDarkerBgP2"], { bold = true }))
M["GruberDarkerBgP3Bold"]      = Highlight.new("GruberDarkerBgP3Bold", with(M["GruberDarkerBgP3"], { bold = true }))
M["GruberDarkerBgP4Bold"]      = Highlight.new("GruberDarkerBgP4Bold", with(M["GruberDarkerBgP4"], { bold = true }))
M["GruberDarkerRedM1Bold"]     = Highlight.new("GruberDarkerRedM1Bold", with(M["GruberDarkerRedM1"], { bold = true }))
M["GruberDarkerRedBold"]       = Highlight.new("GruberDarkerRedBold", with(M["GruberDarkerRed"], { bold = true }))
M["GruberDarkerRedP1Bold"]     = Highlight.new("GruberDarkerRedP1Bold", with(M["GruberDarkerRedP1"], { bold = true }))
M["GruberDarkerGreenBold"]     = Highlight.new("GruberDarkerGreenBold", with(M["GruberDarkerGreen"], { bold = true }))
M["GruberDarkerYellowBold"]    = Highlight.new("GruberDarkerYellowBold", with(M["GruberDarkerYellow"], { bold = true }))
M["GruberDarkerBrownBold"]     = Highlight.new("GruberDarkerBrownBold", with(M["GruberDarkerBrown"], { bold = true }))
M["GruberDarkerQuartzBold"]    = Highlight.new("GruberDarkerQuartzBold", with(M["GruberDarkerQuartz"], { bold = true }))
M["GruberDarkerNiagaraM2Bold"] = Highlight.new("GruberDarkerNiagaraM2Bold", with(M["GruberDarkerNiagaraM2"], { bold = true }))
M["GruberDarkerNiagaraM1Bold"] = Highlight.new("GruberDarkerNiagaraM1Bold", with(M["GruberDarkerNiagaraM1"], { bold = true }))
M["GruberDarkerNiagaraBold"]   = Highlight.new("GruberDarkerNiagaraBold", with(M["GruberDarkerNiagara"], { bold = true }))
M["GruberDarkerWisteriaBold"]  = Highlight.new("GruberDarkerWisteriaBold", with(M["GruberDarkerWisteria"], { bold = true }))

return M
