local M         = {}

local Highlight = require("gruber-darker.highlight")

local colors    = require("gruber-darker.colors")
local bold      = require("gruber-darker.utils").bold


M["GruberDarkerFg"]        = Highlight.new("GruberDarkerFg", { fg = colors["gruber-darker-fg"] })
M["GruberDarkerFgP1"]      = Highlight.new("GruberDarkerFgP1", { fg = colors["gruber-darker-fg+1"] })
M["GruberDarkerFgP2"]      = Highlight.new("GruberDarkerFgP2", { fg = colors["gruber-darker-fg+2"] })
M["GruberDarkerWhite"]     = Highlight.new("GruberDarkerWhite", { fg = colors["gruber-darker-white"] })
M["GruberDarkerBlack"]     = Highlight.new("GruberDarkerBlack", { fg = colors["gruber-darker-black"] })
M["GruberDarkerBgM1"]      = Highlight.new("GruberDarkerBgM1", { fg = colors["gruber-darker-bg-1"] })
M["GruberDarkerBg"]        = Highlight.new("GruberDarkerBg", { fg = colors["gruber-darker-bg"] })
M["GruberDarkerBgP1"]      = Highlight.new("GruberDarkerBgP1", { fg = colors["gruber-darker-bg+1"] })
M["GruberDarkerBgP2"]      = Highlight.new("GruberDarkerBgP2", { fg = colors["gruber-darker-bg+2"] })
M["GruberDarkerBgP3"]      = Highlight.new("GruberDarkerBgP3", { fg = colors["gruber-darker-bg+3"] })
M["GruberDarkerBgP4"]      = Highlight.new("GruberDarkerBgP4", { fg = colors["gruber-darker-bg+4"] })
M["GruberDarkerRedM1"]     = Highlight.new("GruberDarkerRedM1", { fg = colors["gruber-darker-red-1"] })
M["GruberDarkerRed"]       = Highlight.new("GruberDarkerRed", { fg = colors["gruber-darker-red"] })
M["GruberDarkerRedP1"]     = Highlight.new("GruberDarkerRedP1", { fg = colors["gruber-darker-red+1"] })
M["GruberDarkerGreen"]     = Highlight.new("GruberDarkerGreen", { fg = colors["gruber-darker-green"] })
M["GruberDarkerYellow"]    = Highlight.new("GruberDarkerYellow", { fg = colors["gruber-darker-yellow"] })
M["GruberDarkerBrown"]     = Highlight.new("GruberDarkerBrown", { fg = colors["gruber-darker-brown"] })
M["GruberDarkerQuartz"]    = Highlight.new("GruberDarkerQuartz", { fg = colors["gruber-darker-quartz"] })
M["GruberDarkerNiagaraM2"] = Highlight.new("GruberDarkerNiagaraM2", { fg = colors["gruber-darker-niagara-2"] })
M["GruberDarkerNiagaraM1"] = Highlight.new("GruberDarkerNiagaraM1", { fg = colors["gruber-darker-niagara-1"] })
M["GruberDarkerNiagara"]   = Highlight.new("GruberDarkerNiagara", { fg = colors["gruber-darker-niagara"] })
M["GruberDarkerWisteria"]  = Highlight.new("GruberDarkerWisteria", { fg = colors["gruber-darker-wisteria"] })


M["GruberDarkerFgBold"]        = Highlight.new("GruberDarkerFgBold", bold(M["GruberDarkerFg"].opts))
M["GruberDarkerFgP1Bold"]      = Highlight.new("GruberDarkerFgP1Bold", bold(M["GruberDarkerFgP1"].opts))
M["GruberDarkerFgP2Bold"]      = Highlight.new("GruberDarkerFgP2Bold", bold(M["GruberDarkerFgP2"].opts))
M["GruberDarkerWhiteBold"]     = Highlight.new("GruberDarkerWhiteBold", bold(M["GruberDarkerWhite"].opts))
M["GruberDarkerBlackBold"]     = Highlight.new("GruberDarkerBlackBold", bold(M["GruberDarkerBlack"].opts))
M["GruberDarkerBgM1Bold"]      = Highlight.new("GruberDarkerBgM1Bold", bold(M["GruberDarkerBgM1"].opts))
M["GruberDarkerBgBold"]        = Highlight.new("GruberDarkerBgBold", bold(M["GruberDarkerBg"].opts))
M["GruberDarkerBgP1Bold"]      = Highlight.new("GruberDarkerBgP1Bold", bold(M["GruberDarkerBgP1"].opts))
M["GruberDarkerBgP2Bold"]      = Highlight.new("GruberDarkerBgP2Bold", bold(M["GruberDarkerBgP2"].opts))
M["GruberDarkerBgP3Bold"]      = Highlight.new("GruberDarkerBgP3Bold", bold(M["GruberDarkerBgP3"].opts))
M["GruberDarkerBgP4Bold"]      = Highlight.new("GruberDarkerBgP4Bold", bold(M["GruberDarkerBgP4"].opts))
M["GruberDarkerRedM1Bold"]     = Highlight.new("GruberDarkerRedM1Bold", bold(M["GruberDarkerRedM1"].opts))
M["GruberDarkerRedBold"]       = Highlight.new("GruberDarkerRedBold", bold(M["GruberDarkerRed"].opts))
M["GruberDarkerRedP1Bold"]     = Highlight.new("GruberDarkerRedP1Bold", bold(M["GruberDarkerRedP1"].opts))
M["GruberDarkerGreenBold"]     = Highlight.new("GruberDarkerGreenBold", bold(M["GruberDarkerGreen"].opts))
M["GruberDarkerYellowBold"]    = Highlight.new("GruberDarkerYellowBold", bold(M["GruberDarkerYellow"].opts))
M["GruberDarkerBrownBold"]     = Highlight.new("GruberDarkerBrownBold", bold(M["GruberDarkerBrown"].opts))
M["GruberDarkerQuartzBold"]    = Highlight.new("GruberDarkerQuartzBold", bold(M["GruberDarkerQuartz"].opts))
M["GruberDarkerNiagaraM2Bold"] = Highlight.new("GruberDarkerNiagaraM2Bold", bold(M["GruberDarkerNiagaraM2"].opts))
M["GruberDarkerNiagaraM1Bold"] = Highlight.new("GruberDarkerNiagaraM1Bold", bold(M["GruberDarkerNiagaraM1"].opts))
M["GruberDarkerNiagaraBold"]   = Highlight.new("GruberDarkerNiagaraBold", bold(M["GruberDarkerNiagara"].opts))
M["GruberDarkerWisteriaBold"]  = Highlight.new("GruberDarkerWisteriaBold", bold(M["GruberDarkerWisteria"].opts))

return M
